name: Build on pull request
'on':
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    name: Build

  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify