name: Build on pull request
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile the project
        run: mvn --batch-mode compile

      - name: Run tests
        run: mvn --batch-mode test

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
